backend:
  name: git-gateway

media_folder: "src/img" # Folder where user uploaded files should go
# public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "progetti" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Progetto" # Used in the UI, ie.: "New Post"
    folder: "src/progetti" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    format : "json"
    fields: # The fields each document in this collection have
      - {label: "Nome", name: "name", widget: "text"}
      - {label: "Copertina", name: "cover", widget: "image"}
      - {label: "Layout", name: "layout", widget: "hidden", default : "progetto.html"}