--- 
backend: 
  name: git-gateway
collections: 
  - 
    create: true
    fields: 
      - 
        label: Nome
        name: name
        widget: string
      - 
        label: Copertina
        name: cover
        widget: image
      - 
        label: Layout
        name: layout
        widget: string
    folder: src/progetti
    format: json
    label: Progetti
    name: progetti
media_folder: contents/static/img
public_folder: img
